[package]
name = "rspectrum"
version = "0.1.0"
edition = "2021"

authors = ["Ian Knight <ian.knight.1990@gmail.com>"]
readme = "README.md"
repository = "https://github.com/nottsknight/rs-spectrum"
license = "MIT"

[dependencies]
rz80 = { path = "../rz80" }

[dev-dependencies]
rstest = "0.18.2"

